replicaCount: 1

image:
  repository: priya4/user-api
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  targetPort: 5000
  nodePort: 30002
  name: userapi
container:
  name: user-api
